# Generated by Django 5.1.1 on 2025-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothname', models.CharField(max_length=100)),
                ('clothprice', models.IntegerField()),
                ('clothescat', models.CharField(choices=[('printtshirtm', 'Printtshirtm'), ('shirtm', 'Shirtm'), ('oversizem', 'Oversizem'), ('tshirtm', 'Tshirtm'), ('jeansm', 'Jeansm'), ('cargom', 'Cargom'), ('baggym', 'Baggam'), ('shortsm', 'Shortsm'), ('printtshirtw', 'Printtshirtw'), ('shirtw', 'Shirtw'), ('oversizew', 'Oversizew'), ('kurta', 'Kurtaw'), ('pantw', 'pantw'), ('cargow', 'Cargow'), ('cargow', 'Cargow'), ('shortsw', 'Shortsw'), ('braclets', 'Braclets'), ('necklace', 'Necklace'), ('caps', 'Caps'), ('rings', 'Rings'), ('sunglasses', 'Sunglasses'), ('bags', 'Bags'), ('watchm', 'Watchm'), ('watchw', 'Watchw'), ('shoes', 'Shoes')], max_length=200)),
                ('clothesdesc', models.TextField()),
                ('clothimg', models.ImageField(upload_to='')),
            ],
        ),
    ]
