# Generated by Django 5.1.7 on 2025-05-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('cart', models.CharField(default='[]', max_length=255)),
                ('likes', models.CharField(default='[]', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='clothes',
            name='clothescat',
            field=models.CharField(choices=[('printtshirtm', 'Printtshirtm'), ('shirtm', 'Shirtm'), ('jeansm', 'Jeansm'), ('cargom', 'Cargom'), ('baggym', 'Baggam'), ('fullm', 'Fullm'), ('printtshirtw', 'Printtshirtw'), ('hoodies', 'Hoodies'), ('shirtw', 'Shirtw'), ('kurta', 'Kurtaw'), ('cargow', 'Cargow'), ('sareesw', 'Sareesw'), ('braclets', 'Braclets'), ('necklace', 'Necklace'), ('caps', 'Caps'), ('rings', 'Rings'), ('sunglasses', 'Sunglasses'), ('bags', 'Bags'), ('watchm', 'Watchm'), ('watchw', 'Watchw'), ('shoes', 'Shoes'), ('shoesw', 'Shoesw')], max_length=200),
        ),
    ]
