# Generated by Django 5.1.7 on 2025-05-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_users_alter_clothes_clothescat'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='repassword',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
