# Generated by Django 4.2.23 on 2025-06-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_clothes_clothsize_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='clothsize',
            field=models.CharField(default=[], max_length=100, null=True),
        ),
    ]
