from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage),
    path('mencollection', views.mencollection),
    path('womencollection', views.womencollection),
    path('shoes', views.shoes),
    path('shoesw', views.shoesw),
    path('watchm', views.watchm),
    path('watchw', views.watchw),
    path('accessoires', views.accessories),
    path('tshirt', views.tshirt),
    path('shirtm', views.shirtm),
    path('full', views.full),
    path('jeansm', views.jeansm),
    path('cargom', views.cargom),
    path('baggym', views.baggym),
    path('printtshirtw', views.printtshirtw),
    path('hoodies', views.hoodies),
    path('shirtw', views.shirtw),
    path('kurta', views.kurta),
    path('cargow', views.cargow),
    path('sareew', views.sareew),
    path('braclets', views.braclets),
    path('necklace', views.necklace),
    path('caps', views.caps),
    path('rings', views.rings),
    path('sunglasses', views.sunglasses),
    path('bags', views.bags),
    path('watchcoll',views.watchcoll),
    path('shoescoll',views.shoescoll),
    path('productshow/<int:Id>',views.productshow,name='productshow'),
    path('login',views.login),
    path('signup',views.signup),
    path('users',views.userss),
    path('logout',views.logout),
    path('search/<str:item>/', views.search),
    path('addlikeitem/<int:Id>/', views.addlikeitem, name='addlikeitem'),
    path('like',views.like),
    path('addbuyitem/<int:Id>/', views.addbuyitem, name='addbuyitem'),
    path('carts/', views.carts, name='carts'),
    path('addremoveitem/<int:Id>/', views.addremoveitem, name='addremoveitem'),
    path('about',views.about),
    path('privacy',views.privacy),
    path('help',views.help),
    path('term',views.terms)
]
